language: go

go:
    - 1.6rc1
    - 1.5.3
    - tip

install:
    - go get github.com/jteeuwen/go-bindata/...
    - cd client
    - nvm install 5.0
    - nvm use 5.0
    - npm install -g gulp
    - npm install

script:
    - gulp build
    - cd ..
    - go vet ./...
    - go test -v -race ./...
