language: go

go:
    - 1.5.3
    - 1.6
    - tip

install:
    - go get github.com/jteeuwen/go-bindata/...
    - cd client
    - nvm install 4.3.1
    - nvm use 4.3.1
    - npm install -g npm
    - npm install -g gulp
    - npm install

script:
    - gulp build
    - cd ..
    - export GO15VENDOREXPERIMENT=1
    - go vet $(go list ./... | grep -v '/vendor/')
    - go test -v -race $(go list ./... | grep -v '/vendor/')
