language: go

go:
    - 1.4
    - 1.5
    - tip

install:
    - go get golang.org/x/tools/cmd/vet
    - go get github.com/jteeuwen/go-bindata/...
    - cd client
    - nvm install 5.0
    - nvm use 5.0
    - npm install -g gulp
    - npm install

script:
    - gulp -p
    - cd ..
    - go vet ./...
    - go test -v -race ./...
