language: go

go:
    - 1.5.4
    - 1.6.3
    - 1.7.1
    - tip

matrix:
  allow_failures:
    - go: tip

install:
    - go get github.com/jteeuwen/go-bindata/...
    - cd client
    - nvm install 4.6.0
    - nvm use 4.6.0
    - npm install -g yarn
    - npm install -g gulp
    - yarn

script:
    - gulp build
    - cd ..
    - export GO15VENDOREXPERIMENT=1
    - go vet $(go list ./... | grep -v '/vendor/')
    - go test -v -race $(go list ./... | grep -v '/vendor/')
