language: go

go:
  - 1.8.x
  - 1.9.x
  - "1.10"
  - tip

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/jteeuwen/go-bindata/...
  - cd client
  - nvm install 7.10.0
  - nvm use 7.10.0
  - npm install -g yarn
  - npm install -g gulp
  - yarn

script:
  - npm run test:verbose
  - gulp build
  - cd ..
  - go vet $(go list ./... | grep -v '/vendor/')
  - go test -v -race $(go list ./... | grep -v '/vendor/')
